name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'new feature'
  - title: '🔬 Improvements'
    label: 'enhancement'
  - title: '🐞 Bug Fixes'
    label: 'bug'
  - title: '📄 Documentation updates'
    label: 'documentation'
  - title: '🛠️ Development improvements'
    label: 'chore'
  - title: '📦 Dependency updates'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

change-template: |
  * $TITLE ($URL) - @$AUTHOR
  $BODY

template: |
  # 👷 Changes
  $CHANGES

  # 🕺 Contributors 
  $CONTRIBUTORS