name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'new feature'
  - title: '🔬 Improvements'
    label: 'enhancement'
  - title: '🐞 Bug Fixes'
    label: 'bug'
  - title: '📄 Documentation updates'
    label: 'documentation'
  - title: '🛠️ Development improvements'
    label: 'chore'
  - title: '📦 Dependency updates'
    label: 'dependencies'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'

change-template: |
  * $TITLE ($URL) - @$AUTHOR
  $BODY

template: |
  # Changes
  $CHANGES

  # Contributors
  $CONTRIBUTORS